---
- name: Install OpenJDK
  apt: name=openjdk-7-jre-headless state=present

- name: setup group
  group: name={{kafka_group}} system=yes

- name: Setup user
  user: name={{kafka_user}} system=yes group={{kafka_group}}

- name: Fetch kafka binary package
  get_url: dest=/root url="{{apache_mirror}}/kafka/{{kafka_version}}/kafka_2.9.2-{{kafka_version}}.tgz"

- name: Uncompress the kafka tar
  unarchive: copy=no creates=/opt/kafka_2.9.2-{{kafka_version}} dest=/opt src=/root/kafka_2.9.2-{{kafka_version}}.tgz

- name: Link /opt/kafka to the right version
  file: path=/opt/kafka state=link src=/opt/kafka_2.9.2-{{kafka_version}}

- name: create upstart config
  copy: dest={{kafka_upstart_conf}} owner=root group=root mode=644 src=kafka.conf
  notify:
    - restart kafka
  when: ansible_distribution_release == 'trusty'

- name: create systemd config
  copy: dest={{kafka_systemd_service}} owner=root group=root mode=644 src=kafka.service
  notify:
    - restart kafka
  when: ansible_distribution_release != 'trusty'

- name: Create data_dir
  file: path={{kafka_data_dir}} state=directory owner={{kafka_user}} group={{kafka_group}} mode=755

- name: Remove lost+found in the datadir
  file: path="{{kafka_data_dir}}/lost+found" state=absent

- name: Create log_dir
  file: path={{kafka_log_dir}} state=directory owner={{kafka_user}} group={{kafka_group}} mode=755

- name: link conf_dir to /opt/kafka/config
  file: path={{kafka_conf_dir}} state=link src=/opt/kafka/config

# Setup log4j.properties
- name: create log4j.properties
  template: dest="{{kafka_conf_dir}}/log4j.properties" owner={{kafka_user}} group={{kafka_group}} mode=644 src=log4j.properties.j2
  notify:
    - restart kafka

# Setup server.properties
- name: create server.properties
  template: dest="{{kafka_conf_dir}}/server.properties" owner={{kafka_user}} group={{kafka_group}} mode=640 src=server.properties.j2
  notify:
    - restart kafka
